[project]
name = "technical-interview"
version = "0.1.0"
description = "A project that contains the technical interview challenge for Mirico"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.0",
    "geopy>=2.4.1",
    "nmea>=0.1.4",
    "nmea-parser>=0.5.0",
    "pandas>=3.0.0",
    "pyinstaller>=6.18.0",
    "pynmeagps>=1.1.0",
    "pytest>=9.0.2",
    "requests>=2.32.5",
    "sqlalchemy>=2.0.46",
    "sqlmodel>=0.0.31",
]

[dependency-groups]
dev = [
    "alembic>=1.18.1",
    "fastapi[standard]>=0.128.0",
    "ruff>=0.14.14",
    "ty>=0.0.14",
]


[tool.alembic]

# path to migration scripts.
# this is typically a path given in POSIX (e.g. forward slashes)
# format, relative to the token %(here)s which refers to the location of this
# ini file
script_location = "%(here)s/alembic"

# additional paths to be prepended to sys.path. defaults to the current working directory.
prepend_sys_path = [
    "."
]

[[tool.alembic.post_write_hooks]]
# lint with attempts to fix using "ruff" - use the module runner, against the "ruff" module
name = "ruff"
type = "module"
module = "ruff"
options = "check --fix REVISION_SCRIPT_FILENAME"
