"""Initial migration

Revision ID: 5a949e4d4b3b
Revises:
Create Date: 2026-01-29 12:58:43.013361

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "5a949e4d4b3b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicle",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number_plate", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("vehicle", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_vehicle_number_plate"), ["number_plate"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vehicle", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vehicle_number_plate"))

    op.drop_table("vehicle")
    # ### end Alembic commands ###
