"""Add location model

Revision ID: 861e15100ce7
Revises: 5a949e4d4b3b
Create Date: 2026-01-29 14:44:02.241828

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "861e15100ce7"
down_revision: Union[str, Sequence[str], None] = "5a949e4d4b3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("hae", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicle.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("location", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_location_timestamp"), ["timestamp"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("location", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_location_timestamp"))

    op.drop_table("location")
    # ### end Alembic commands ###
